In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [4]:
arr = np.array(list1)
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr[0]

1

In [7]:
arr[-1]

5

In [8]:
arr[2] = 100
arr

array([  1,   2, 100,   4,   5])

In [9]:
arr[5] = 121

IndexError: index 5 is out of bounds for axis 0 with size 5

In [10]:
len(arr)

5

In [11]:
arr.size  # Total number of elements

5

In [12]:
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]
matrix1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
arr2 = np.array(matrix1)
type(arr2)

numpy.ndarray

In [14]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr2.T  # Transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [15]:
len(arr2) # number of rows

3

In [17]:
len(arr2[0]) # number of rows

3

In [18]:
len(arr2[1]) # number of columns

3

In [16]:
arr2.size # Total number of elements

9

In [19]:
arr.shape # shape is an attribute, not a method

(5,)

In [20]:
arr.shape[0]

5

In [25]:
arr2.shape

(3, 3)

In [22]:
arr2.shape[0]

3

In [23]:
arr2.shape[1]

3

In [26]:
arr2.shape[0] * arr2.shape[1]

9

In [27]:
arr2.size

9

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
np.arange(1,10,2) # start is needed when we specify step

array([1, 3, 5, 7, 9])

In [39]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [38]:
arr.dtype

dtype('float64')

In [40]:
arr = np.zeros(5, dtype=int)
arr

array([0, 0, 0, 0, 0])

In [41]:
arr.dtype

dtype('int64')

In [44]:
np.zeros((5,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [45]:
np.ones(4)

array([1., 1., 1., 1.])

In [46]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
np.linspace(0,10,3) # evenly spaced elements over the specified interval (inclusive)

array([ 0.,  5., 10.])

In [48]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [49]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [50]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [55]:
arr2 = np.eye(4)
arr2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:
arr2.T

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
np.random.rand(3)

array([0.5113973 , 0.16883893, 0.58622497])

In [58]:
np.random.rand(6)

array([0.84321221, 0.40966703, 0.1162222 , 0.32526448, 0.58167946,
       0.36438206])

In [59]:
np.random.rand(3,4)

array([[0.09510635, 0.57840267, 0.74377758, 0.93078915],
       [0.99265183, 0.52220278, 0.34719848, 0.02424184],
       [0.61852045, 0.52084876, 0.34619215, 0.27811837]])

In [60]:
np.random.randn(3)

array([-0.33855351,  0.58012161,  1.25299389])

In [61]:
np.random.randn(6)

array([-0.68468786,  1.96302166, -0.03712211, -0.58346176,  0.28498614,
       -1.18898338])

In [62]:
np.random.randn(5,5)

array([[ 0.54231003,  0.23745108, -0.0319818 , -0.97685359, -1.11192332],
       [-0.32897383,  1.74104052, -0.0252456 ,  0.74266911,  0.74509633],
       [ 0.45005656, -1.30780932,  1.98301638, -2.21192027,  0.30210787],
       [ 0.60663921,  0.95107094,  0.59791453, -1.99624395,  0.7540201 ],
       [-0.27515941,  1.0962052 , -0.20941109, -0.58578083, -0.34995474]])

In [65]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

In [66]:
np.random.seed(42)
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

In [71]:
np.random.randint(1,100) # 1 is inclusive and 100 is exclusive

75

In [81]:
arr = np.random.randint(1,100,10)
arr

array([89, 60, 41, 29, 15, 45, 65, 89, 71,  9])

In [82]:
arr.min()

9

In [83]:
arr.argmin()

9

In [84]:
arr.max()

89

In [85]:
arr.argmax()

0

In [86]:
arr.mean()

51.3

In [88]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [89]:
arr.shape

(25,)

In [90]:
arr2 = arr.reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [91]:
arr2.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [92]:
arr2.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [94]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [95]:
arr2.shape

(5, 5)

In [96]:
arr2.reshape(25,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [97]:
arr2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [98]:
matrix1 = np.array([[1,2],[3,4]])
matrix1

array([[1, 2],
       [3, 4]])

In [99]:
np.sqrt(matrix1)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [100]:
np.square(matrix1)

array([[ 1,  4],
       [ 9, 16]])

In [101]:
np.sum(matrix1)

10

In [102]:
np.min(matrix1)

1

In [103]:
np.max(matrix1)

4

In [104]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
arr[0] = 10
arr

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
arr[2:5] = 100  # broadcasting
arr

array([ 10,   2, 100, 100, 100,   6,   7,   8,   9,  10])

In [108]:
arr[:] = 111
arr

array([111, 111, 111, 111, 111, 111, 111, 111, 111, 111])

In [109]:
arr

array([111, 111, 111, 111, 111, 111, 111, 111, 111, 111])

In [110]:
arr2 = arr
arr2

array([111, 111, 111, 111, 111, 111, 111, 111, 111, 111])

In [111]:
arr is arr2 # True implies they are same array

True

In [112]:
arr2[3] = 1234
arr

array([ 111,  111,  111, 1234,  111,  111,  111,  111,  111,  111])

In [113]:
arr

array([ 111,  111,  111, 1234,  111,  111,  111,  111,  111,  111])

In [114]:
arr2 = arr.copy()
arr is arr2

False

In [115]:
arr2[5] = 444
arr2

array([ 111,  111,  111, 1234,  111,  444,  111,  111,  111,  111])

In [116]:
arr

array([ 111,  111,  111, 1234,  111,  111,  111,  111,  111,  111])

In [118]:
arr2 = np.zeros((10,10))
arr2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [119]:
for i in range(arr2.shape[1]):
    arr2[i] = i
    
arr2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [120]:
arr2[[0,2,4,6,8]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [123]:
arr2[arr2 % 2 == 0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

In [124]:
arr2 + arr2

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [16., 16., 16., 16., 16., 16., 16., 16., 16., 16.],
       [18., 18., 18., 18., 18., 18., 18., 18., 18., 18.]])

In [125]:
arr2 - arr2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [126]:
arr2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [127]:
arr2 * 3

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [15., 15., 15., 15., 15., 15., 15., 15., 15., 15.],
       [18., 18., 18., 18., 18., 18., 18., 18., 18., 18.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [24., 24., 24., 24., 24., 24., 24., 24., 24., 24.],
       [27., 27., 27., 27., 27., 27., 27., 27., 27., 27.]])

In [128]:
arr2 / 3

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
        0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.66666667, 0.66666667, 0.66666667, 0.66666667, 0.66666667,
        0.66666667, 0.66666667, 0.66666667, 0.66666667, 0.66666667],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.33333333, 1.33333333, 1.33333333, 1.33333333, 1.33333333,
        1.33333333, 1.33333333, 1.33333333, 1.33333333, 1.33333333],
       [1.66666667, 1.66666667, 1.66666667, 1.66666667, 1.66666667,
        1.66666667, 1.66666667, 1.66666667, 1.66666667, 1.66666667],
       [2.        , 2.        , 2.        , 2.        , 2.        ,
        2.        , 2.        , 2.        , 2.        , 2.        ],
       [2.33333333, 2.33333333, 2.3333333

In [129]:
1/arr2

/tmp/ipykernel_69077/1672552411.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr2


array([[       inf,        inf,        inf,        inf,        inf,
               inf,        inf,        inf,        inf,        inf],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.5       , 0.5       , 0.5       , 0.5       , 0.5       ,
        0.5       , 0.5       , 0.5       , 0.5       , 0.5       ],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
        0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.25      , 0.25      , 0.25      , 0.25      , 0.25      ,
        0.25      , 0.25      , 0.25      , 0.25      , 0.25      ],
       [0.2       , 0.2       , 0.2       , 0.2       , 0.2       ,
        0.2       , 0.2       , 0.2       , 0.2       , 0.2       ],
       [0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.16666667,
        0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.16666667],
       [0.14285714, 0.14285714, 0.1428571

In [130]:
arr2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [131]:
np.log(arr2)

/tmp/ipykernel_69077/2430268246.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr2)


array([[      -inf,       -inf,       -inf,       -inf,       -inf,
              -inf,       -inf,       -inf,       -inf,       -inf],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.69314718, 0.69314718, 0.69314718, 0.69314718, 0.69314718,
        0.69314718, 0.69314718, 0.69314718, 0.69314718, 0.69314718],
       [1.09861229, 1.09861229, 1.09861229, 1.09861229, 1.09861229,
        1.09861229, 1.09861229, 1.09861229, 1.09861229, 1.09861229],
       [1.38629436, 1.38629436, 1.38629436, 1.38629436, 1.38629436,
        1.38629436, 1.38629436, 1.38629436, 1.38629436, 1.38629436],
       [1.60943791, 1.60943791, 1.60943791, 1.60943791, 1.60943791,
        1.60943791, 1.60943791, 1.60943791, 1.60943791, 1.60943791],
       [1.79175947, 1.79175947, 1.79175947, 1.79175947, 1.79175947,
        1.79175947, 1.79175947, 1.79175947, 1.79175947, 1.79175947],
       [1.94591015, 1.94591015, 1.9459101

In [132]:
np.log10(arr2)

/tmp/ipykernel_69077/2101587253.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr2)


array([[      -inf,       -inf,       -inf,       -inf,       -inf,
              -inf,       -inf,       -inf,       -inf,       -inf],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.30103   , 0.30103   , 0.30103   , 0.30103   , 0.30103   ,
        0.30103   , 0.30103   , 0.30103   , 0.30103   , 0.30103   ],
       [0.47712125, 0.47712125, 0.47712125, 0.47712125, 0.47712125,
        0.47712125, 0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999, 0.60205999,
        0.60205999, 0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   , 0.69897   ,
        0.69897   , 0.69897   , 0.69897   , 0.69897   , 0.69897   ],
       [0.77815125, 0.77815125, 0.77815125, 0.77815125, 0.77815125,
        0.77815125, 0.77815125, 0.77815125, 0.77815125, 0.77815125],
       [0.84509804, 0.84509804, 0.8450980

In [133]:
np.log2(arr2)

/tmp/ipykernel_69077/3659630883.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(arr2)


array([[      -inf,       -inf,       -inf,       -inf,       -inf,
              -inf,       -inf,       -inf,       -inf,       -inf],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.5849625 , 1.5849625 , 1.5849625 , 1.5849625 , 1.5849625 ,
        1.5849625 , 1.5849625 , 1.5849625 , 1.5849625 , 1.5849625 ],
       [2.        , 2.        , 2.        , 2.        , 2.        ,
        2.        , 2.        , 2.        , 2.        , 2.        ],
       [2.32192809, 2.32192809, 2.32192809, 2.32192809, 2.32192809,
        2.32192809, 2.32192809, 2.32192809, 2.32192809, 2.32192809],
       [2.5849625 , 2.5849625 , 2.5849625 , 2.5849625 , 2.5849625 ,
        2.5849625 , 2.5849625 , 2.5849625 , 2.5849625 , 2.5849625 ],
       [2.80735492, 2.80735492, 2.8073549

In [134]:
arr2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [135]:
np.sin(arr2)

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.84147098,  0.84147098,  0.84147098,  0.84147098,  0.84147098,
         0.84147098,  0.84147098,  0.84147098,  0.84147098,  0.84147098],
       [ 0.90929743,  0.90929743,  0.90929743,  0.90929743,  0.90929743,
         0.90929743,  0.90929743,  0.90929743,  0.90929743,  0.90929743],
       [ 0.14112001,  0.14112001,  0.14112001,  0.14112001,  0.14112001,
         0.14112001,  0.14112001,  0.14112001,  0.14112001,  0.14112001],
       [-0.7568025 , -0.7568025 , -0.7568025 , -0.7568025 , -0.7568025 ,
        -0.7568025 , -0.7568025 , -0.7568025 , -0.7568025 , -0.7568025 ],
       [-0.95892427, -0.95892427, -0.95892427, -0.95892427, -0.95892427,
        -0.95892427, -0.95892427, -0.95892427, -0.95892427, -0.95892427],
       [-0.2794155 , -0.2794155 , -0.2794155 , -0.2794155 , -0.2794155 ,
        -0.2794155 , -0.2794155 , -0.2794155 